let btn = document.querySelector(".btn");
let bgColorTxt = document.getElementById("color");
let bg = document.querySelector("#bg");

let colors = [
  "Red",
  "Blue",
  "Green",
  "Orange",
  "Purple",
  "Aqua",
  "Pink",
  "Beice",
  "BlueViolet",
  "Olive",
  "LawnGreen",
  "Magenta",
  "LightGreen",
  "RosyBrown",
  "MidnightBlue",
  "LimeGreen",
  "Teal",
  "DarkTurquoise",
  "IndianRed",
  "LightCoral",
  "Salmon",
  "DarkSalmon	",
  "LightSalmon",
  "Crimson",
  "FireBrick",
  "DarkRed",
  "LightPink",
  "HotPink",
  "DeepPink",
  "MediumVioletRed",
  "PaleVioletRed",
  "LightSalmon",
  "Coral",
  "Tomato",
  "OrangeRed",
  "DarkOrange",
  "Gold",
  "LightYellow",
  "LemonChiffon",
  "LightGoldenrodYellow",
  "PapayaWhip",
  "Moccasin",
  "PeachPuff",
  "PaleGoldenrod",
  "Khaki",
  "DarkKhaki",
  "Lavender",
  "Thistle",
  "Plum",
  "Violet",
  "Orchid",
  "Fuchsia",
  "MediumOrchid	",
  "MediumPurple",
  "RebeccaPurple",
  "DarkViolet",
  "DarkOrchid",
  "DarkMagenta",
  "Indigo",
  "SlateBlue",
  "DarkSlateBlue",
  "MediumSlateBlue",
  "Chartreuse",
  "Lime",
  "PaleGreen",
  "MediumSpringGreen",
  "SpringGreen",
  "MediumSeaGreen",
  "SeaGreen",
  "ForestGreen",
  "YellowGreen",
  "OliveDrab",
  "DarkOliveGreen",
  "MediumAquamarine",
  "DarkSeaGreen",
  "LightCyan",
  "PaleTurquoise",
  "CadetBlue",
  "Navy",
  "Cornsilk",
  "Peru",
  "Sienna",
  "Ivory",
  "SlateGray",
];

btn.addEventListener("click", () => {
  let num = Math.floor(Math.random() * colors.length);

  bg.style.background = colors[num];

  colors.splice(num, 1);

  bgColorTxt.innerHTML = bg.style.background.replace("background: ", "");

  console.log(colors);
});
